version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./KC.NanoProcesses/KC.NanoProcesses.csproj --verbosity m
build_script:
  # output will be in ./KC.NanoProcesses/bin/Release/netstandard2.0/
  - cmd: dotnet build -c Release ./KC.NanoProcesses/KC.NanoProcesses.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: './KC.NanoProcesses/bin/Release/*.nupkg'
   name: NuGet
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Test_NanoProcesses/Test_NanoProcesses.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd Test_NanoProcesses
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy:
 - provider: NuGet
   api_key:
     secure: RqN8h1cc9RDQzU+gkhf0YclC7prs0yhULZ4grxJUuPE3mfR7ho76wXt2eGXjcAbk
   skip_symbols: true