version: '1.0.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./KC.Actin/KC.Actin.csproj --verbosity m
build_script:
  # output will be in ./KC.Actin/bin/Release/netstandard2.0/
  - cmd: dotnet build -c Release ./KC.Actin/KC.Actin.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: './KC.Actin/bin/Release/*.nupkg'
   name: NuGet
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Test_Actin/Test.Actin.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd Test_Actin
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy:
 - provider: NuGet
   api_key:
     secure: 6w3Tbz5ydXbG4fmqd05S6st5bN5uAKwd7RULqZtQhD+pMKBc+V5+trKUt2rlappG
   skip_symbols: true